---
abstract: Generate easily flowcharts as Graph::Easy objects
author:
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.68
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Graph-Flowchart
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  Graph::Easy::As_svg: 0.22
  Graph::Easy::Manual: 0.4
requires:
  Graph::Easy: 0.6
  perl: 5.8.1
version: 0.11
