---
name: Graph-Flowchart
version: 0.09
version_from: lib/Graph/Flowchart.pm
license: gpl
distribution_type: module
generated_by: Graph-Flowchart version 0.09
installdirs: site
requires:
  Graph::Easy: 0.4
